# Generated by Django 5.2.4 on 2025-07-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=30)),
                ('nazwisko', models.CharField(max_length=30)),
                ('pesel', models.CharField(max_length=11)),
                ('stanowisko', models.CharField(max_length=50)),
                ('data_zatrudnienia', models.DateField()),
                ('data_urodzenia', models.DateField()),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('data_modyfikacji', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
