# Generated by Django 5.2.4 on 2025-07-16 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracownicy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zespol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, unique=True)),
                ('opis', models.TextField(blank=True, null=True)),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('data_modyfikacji', models.DateTimeField(auto_now=True)),
                ('lider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zespoly_liderem', to='pracownicy.pracownik')),
            ],
            options={
                'verbose_name': 'Zespół',
                'verbose_name_plural': 'Zespoły',
                'ordering': ['nazwa'],
            },
        ),
        migrations.AddField(
            model_name='pracownik',
            name='zespol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pracownicy', to='pracownicy.zespol'),
        ),
    ]
