# Generated by Django 5.2.4 on 2025-07-16 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracownicy', '0002_zespol_pracownik_zespol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pracownik',
            name='rola',
            field=models.CharField(choices=[('admin', 'Admin'), ('hr', 'Pani Anetka'), ('ceo', 'CEO'), ('kierownik', 'Kierownik'), ('pracownik', 'Pracownik')], default='pracownik', max_length=20),
        ),
        migrations.AddField(
            model_name='pracownik',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
