# Generated by Django 5.2.4 on 2025-07-17 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pracownicy', '0003_pracownik_rola_pracownik_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pracownik',
            options={'permissions': [('can_view_salary', 'Can view salary information'), ('can_manage_hr', 'Can manage HR tasks'), ('can_view_all_employees', 'Can view all employees'), ('can_export_data', 'Can export employee data'), ('can_approve_leave', 'Can approve leave requests'), ('can_access_reports', 'Can access management reports')]},
        ),
    ]
