# Generated by Django 5.2.4 on 2025-07-17 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pracownicy', '0004_alter_pracownik_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pracownik',
            options={'permissions': [('can_manage_system', 'Can manage system (reset DB, import/export)'), ('can_manage_users_and_roles', 'Can manage users and roles'), ('can_view_all_data', 'Can view and modify all data (employees, reports, logs)'), ('can_manage_employees', 'Can add/remove/edit employees'), ('can_view_personal_data', 'Can access personal employee data'), ('can_view_all_users', 'Can view all users'), ('can_view_strategic_data', 'Can view strategic data and insights'), ('can_manage_team', 'Can manage employees in own team'), ('can_view_team_data', 'Can view team data and reports'), ('can_view_own_profile', 'Can view own profile'), ('can_update_own_contact', 'Can update own contact info and password')]},
        ),
    ]
