# Generated by Django 5.2.4 on 2025-07-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracownicy', '0005_alter_pracownik_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pracownik',
            name='rola',
            field=models.CharField(choices=[('admin', 'Administrator Systemu'), ('hr', 'Specjalista HR'), ('ceo', 'Dyrektor Generalny'), ('kierownik', 'Kierownik Zespołu'), ('senior_dev', 'Senior Developer'), ('dev', 'Developer'), ('analyst', 'Analityk'), ('tester', 'Tester'), ('designer', 'Designer'), ('marketing_spec', 'Specjalista ds. Marketingu'), ('sales_rep', 'Przedstawiciel Handlowy'), ('accountant', 'Księgowy'), ('support', 'Wsparcie Techniczne'), ('intern', 'Stażysta'), ('pracownik', 'Pracownik')], default='pracownik', max_length=20),
        ),
    ]
