# Generated by Django 5.2.4 on 2025-07-21 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracownicy', '0008_alter_pracownik_rola_alter_pracownik_stanowisko'),
    ]

    operations = [
        migrations.AddField(
            model_name='pracownik',
            name='dzial',
            field=models.CharField(blank=True, help_text='Np. Dział 1, Dział 2', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pracownik',
            name='przelozony',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='podwladni', to='pracownicy.pracownik'),
        ),
        migrations.AlterField(
            model_name='pracownik',
            name='rola',
            field=models.CharField(choices=[('admin', 'Administrator Systemu'), ('hr', 'Specjalista HR'), ('ceo', 'Dyrektor Generalny'), ('kierownik', 'Kierownik Zespołu'), ('przelozony_dzialu', 'Przełożony Działu'), ('marketing_spec', 'Specjalista ds. Marketingu'), ('sales_rep', 'Przedstawiciel Handlowy'), ('accountant', 'Księgowy'), ('support', 'Wsparcie Techniczne'), ('intern', 'Stażysta'), ('pracownik', 'Pracownik')], default='pracownik', max_length=20),
        ),
        migrations.AlterField(
            model_name='pracownik',
            name='stanowisko',
            field=models.CharField(choices=[('admin', 'Administrator'), ('junior_dev', 'Junior Developer'), ('senior_dev', 'Senior Developer'), ('team_lead', 'Team Leader'), ('project_manager', 'Project Manager'), ('hr_specialist', 'Specjalista HR'), ('recruiter', 'Rekruter'), ('accountant', 'Księgowy'), ('financial_analyst', 'Analityk Finansowy'), ('marketing_specialist', 'Specjalista Marketingu'), ('sales_rep', 'Przedstawiciel Handlowy'), ('sales_manager', 'Menedżer Sprzedaży'), ('support_specialist', 'Specjalista Wsparcia'), ('system_admin', 'Administrator Systemu'), ('business_analyst', 'Analityk Biznesowy'), ('ux_designer', 'UX Designer'), ('qa_tester', 'Tester QA'), ('intern', 'Stażysta'), ('ceo', 'Dyrektor Generalny'), ('cto', 'Dyrektor Techniczny'), ('cfo', 'Dyrektor Finansowy'), ('programista', 'Programista')], max_length=50),
        ),
    ]
