# Generated by Django 5.2.4 on 2025-07-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracownicy', '0010_alter_pracownik_dzial_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50, unique=True)),
                ('opis', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Rola',
                'verbose_name_plural': 'Role',
                'ordering': ['nazwa'],
            },
        ),
    ]
