# Generated by Django 5.2.4 on 2025-07-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracownicy', '0011_rola'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stanowisko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, unique=True)),
                ('kod', models.CharField(default='default', help_text='Unikalny kod stanowiska (np. dev, manager)', max_length=20, unique=True)),
                ('opis', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Stanowisko',
                'verbose_name_plural': 'Stanowiska',
                'ordering': ['nazwa'],
            },
        ),
        migrations.AlterModelOptions(
            name='rola',
            options={'ordering': ['poziom_uprawnien', 'nazwa'], 'verbose_name': 'Rola', 'verbose_name_plural': 'Role'},
        ),
        migrations.AddField(
            model_name='rola',
            name='kod',
            field=models.CharField(default='default', help_text='Unikalny kod roli (np. admin, hr)', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='rola',
            name='poziom_uprawnien',
            field=models.IntegerField(choices=[(0, 'Administrator (najwyższy poziom)'), (1, 'Kierownictwo wysokie (CEO, CTO)'), (2, 'HR i zarządzanie'), (3, 'Kierownictwo średnie (kierownik działu)'), (4, 'Kierownictwo niskie (team leader)'), (5, 'Specjalista'), (6, 'Pracownik podstawowy'), (7, 'Stażysta (najniższy poziom)')], default=6, help_text='Poziom uprawnień - niższa liczba = wyższe uprawnienia'),
        ),
        migrations.AddField(
            model_name='zespol',
            name='kod',
            field=models.CharField(default='default', help_text='Unikalny kod zespołu (np. hr, it)', max_length=20, unique=True),
        ),
    ]
