# Generated by Django 5.2.4 on 2025-07-28 07:20

import pracownicy.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracownicy', '0012_stanowisko_alter_rola_options_rola_kod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pracownik',
            name='pesel',
            field=models.CharField(max_length=11, validators=[pracownicy.validators.validate_pesel]),
        ),
    ]
