# Generated by Django 5.2.4 on 2025-07-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracownicy', '0013_alter_pracownik_pesel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pracownik',
            name='zarobki',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Miesięczne wynagrodzenie brutto w PLN', max_digits=10, null=True),
        ),
    ]
