# Generated by Django 5.2.4 on 2025-07-28 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pracownicy', '0014_pracownik_zarobki'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pracownik',
            name='zarobki',
        ),
    ]
