# Generated by Django 5.2.4 on 2025-07-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracownicy', '0015_remove_pracownik_zarobki'),
    ]

    operations = [
        migrations.AddField(
            model_name='pracownik',
            name='zarobki',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Miesięczne wynagrodzenie brutto w PLN', max_digits=10, null=True, verbose_name='Zarobki'),
        ),
    ]
