# Generated by Django 5.2.4 on 2025-07-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracownicy', '0016_pracownik_zarobki'),
    ]

    operations = [
        migrations.AddField(
            model_name='pracownik',
            name='data_ostatniej_oceny',
            field=models.DateField(blank=True, help_text='Kiedy była wykonana ostatnia ocena', null=True, verbose_name='Data ostatniej oceny'),
        ),
        migrations.AddField(
            model_name='pracownik',
            name='komentarz_oceny',
            field=models.TextField(blank=True, help_text='Dodatkowe uwagi do oceny pracownika', null=True, verbose_name='Komentarz do oceny'),
        ),
        migrations.AddField(
            model_name='pracownik',
            name='ocena',
            field=models.IntegerField(blank=True, choices=[(1, '⭐ - Niewystarczająca'), (2, '⭐⭐ - Poniżej oczekiwań'), (3, '⭐⭐⭐ - Zadowalająca'), (4, '⭐⭐⭐⭐ - Dobra'), (5, '⭐⭐⭐⭐⭐ - Doskonała')], help_text='Ostatnia ocena pracownika (1-5 gwiazdek)', null=True, verbose_name='Ocena pracownika'),
        ),
    ]
