# Generated by Django 5.2.4 on 2025-07-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracownicy', '0017_pracownik_data_ostatniej_oceny_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pracownik',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
        migrations.AddField(
            model_name='pracownik',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
