# Generated by Django 5.2.4 on 2025-07-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracownicy', '0018_pracownik_cv_pracownik_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pracownik',
            name='dyplom',
            field=models.FileField(blank=True, null=True, upload_to='dokumenty/dyplomy/', verbose_name='Dyplom/Certyfikat'),
        ),
        migrations.AddField(
            model_name='pracownik',
            name='inne_dokumenty',
            field=models.FileField(blank=True, null=True, upload_to='dokumenty/inne/', verbose_name='Inne dokumenty'),
        ),
        migrations.AddField(
            model_name='pracownik',
            name='swiadectwo_pracy',
            field=models.FileField(blank=True, null=True, upload_to='dokumenty/swiadectwa/', verbose_name='Świadectwo pracy'),
        ),
        migrations.AddField(
            model_name='pracownik',
            name='umowa_pracy',
            field=models.FileField(blank=True, null=True, upload_to='dokumenty/umowy/', verbose_name='Umowa o pracę'),
        ),
        migrations.AddField(
            model_name='pracownik',
            name='zdjecie',
            field=models.ImageField(blank=True, null=True, upload_to='dokumenty/zdjecia/', verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='pracownik',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='dokumenty/cv/', verbose_name='CV'),
        ),
    ]
