# Generated by Django 5.2.4 on 2025-07-29 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracownicy', '0019_pracownik_dyplom_pracownik_inne_dokumenty_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DzienPracy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('czas_wejscia', models.TimeField(blank=True, null=True)),
                ('czas_wyjscia', models.TimeField(blank=True, null=True)),
                ('czas_przerw', models.DurationField(blank=True, help_text='Łączny czas przerw', null=True)),
                ('czas_pracy', models.DurationField(blank=True, help_text='Łączny czas pracy', null=True)),
                ('status_dnia', models.CharField(choices=[('obecny', 'Obecny'), ('nieobecny', 'Nieobecny'), ('urlop', 'Urlop'), ('choroba', 'Zwolnienie lekarskie'), ('swieto', 'Święto'), ('delegacja', 'Delegacja')], default='nieobecny', max_length=15)),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('data_modyfikacji', models.DateTimeField(auto_now=True)),
                ('pracownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dni_pracy', to='pracownicy.pracownik')),
            ],
            options={
                'verbose_name': 'Dzień pracy',
                'verbose_name_plural': 'Dni pracy',
                'ordering': ['-data'],
                'indexes': [models.Index(fields=['pracownik', 'data'], name='pracownicy__pracown_449221_idx'), models.Index(fields=['data'], name='pracownicy__data_aa7061_idx')],
                'unique_together': {('pracownik', 'data')},
            },
        ),
        migrations.CreateModel(
            name='Obecnosc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_czas', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('wejscie', 'Wejście'), ('wyjscie', 'Wyjście'), ('przerwa_start', 'Początek przerwy'), ('przerwa_koniec', 'Koniec przerwy')], max_length=15)),
                ('lokalizacja', models.CharField(blank=True, help_text='Opcjonalna lokalizacja odbicia (np. biuro, praca zdalna)', max_length=100, null=True)),
                ('adres_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('uwagi', models.TextField(blank=True, null=True)),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('pracownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obecnosci', to='pracownicy.pracownik')),
                ('zmodyfikowane_przez', models.ForeignKey(blank=True, help_text='Użytkownik który zmodyfikował rekord', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Obecność',
                'verbose_name_plural': 'Obecności',
                'ordering': ['-data_czas'],
                'indexes': [models.Index(fields=['pracownik', 'data_czas'], name='pracownicy__pracown_420810_idx'), models.Index(fields=['data_czas'], name='pracownicy__data_cz_907ff3_idx')],
            },
        ),
    ]
