# Generated by Django 5.2.4 on 2025-08-08 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracownicy', '0020_dzienpracy_obecnosc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zadanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=200, verbose_name='Tytuł zadania')),
                ('opis', models.TextField(blank=True, null=True, verbose_name='Opis')),
                ('status', models.CharField(choices=[('nowe', 'Nowe'), ('w_toku', 'W trakcie'), ('wykonane', 'Wykonane'), ('anulowane', 'Anulowane'), ('przeterminowane', 'Przeterminowane')], default='nowe', max_length=20)),
                ('priorytet', models.CharField(choices=[('niski', '🟢 Niski'), ('normalny', '🟡 Normalny'), ('wysoki', '🟠 Wysoki'), ('krytyczny', '🔴 Krytyczny')], default='normalny', max_length=20)),
                ('termin', models.DateTimeField(blank=True, null=True, verbose_name='Termin wykonania')),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('data_modyfikacji', models.DateTimeField(auto_now=True)),
                ('data_wykonania', models.DateTimeField(blank=True, null=True, verbose_name='Data wykonania')),
                ('przypisane_do', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zadania', to='pracownicy.pracownik', verbose_name='Przypisane do')),
                ('utworzone_przez', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utworzone_zadania', to='pracownicy.pracownik', verbose_name='Utworzone przez')),
            ],
            options={
                'verbose_name': 'Zadanie',
                'verbose_name_plural': 'Zadania',
                'ordering': ['-data_utworzenia'],
            },
        ),
    ]
