# Generated by Django 5.2.4 on 2025-08-08 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracownicy', '0021_zadanie'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcenaPracownika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategoria', models.CharField(choices=[('komunikacja', '💬 Komunikacja'), ('praca_zespolowa', '🤝 Praca zespołowa'), ('kreatywnosc', '💡 Kreatywność'), ('punktualnosc', '⏰ Punktualność'), ('zaangazowanie', '🔥 Zaangażowanie'), ('umiejetnosci_tech', '💻 Umiejętności techniczne'), ('liderstwo', '👑 Liderstwo'), ('rozwiazywanie_problemow', '🧩 Rozwiązywanie problemów')], max_length=30, verbose_name='Kategoria')),
                ('ocena', models.IntegerField(choices=[(1, '1 ⭐ - Wymaga poprawy'), (2, '2 ⭐⭐ - Poniżej oczekiwań'), (3, '3 ⭐⭐⭐ - Dobrze'), (4, '4 ⭐⭐⭐⭐ - Bardzo dobrze'), (5, '5 ⭐⭐⭐⭐⭐ - Doskonale')], verbose_name='Ocena')),
                ('komentarz', models.TextField(blank=True, null=True, verbose_name='Komentarz')),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('anonimowa', models.BooleanField(default=False, verbose_name='Ocena anonimowa')),
                ('oceniajacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dane_oceny', to='pracownicy.pracownik', verbose_name='Oceniający')),
                ('oceniany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otrzymane_oceny', to='pracownicy.pracownik', verbose_name='Oceniany')),
            ],
            options={
                'verbose_name': 'Ocena pracownika',
                'verbose_name_plural': 'Oceny pracowników',
                'ordering': ['-data_utworzenia'],
                'unique_together': {('oceniajacy', 'oceniany', 'kategoria')},
            },
        ),
    ]
